Let's check whether a given tensor is symmetric or not?

In [1]:
import numpy as np

In [2]:
def Ttranspose(A):
    n,m,p=A.shape
    AT=np.zeros((m,n,p),dtype=complex)
    AFFT=np.fft.fft(A,axis=2)
    for i in range(3):
        AT[:,:,i]=AFFT[:,:,i].T
    ATT=np.fft.ifft(AT,axis=2).real
    return ATT

In [3]:
def tProduct(A,B):
    n,m,p=A.shape
    m1,n1,p1=B.shape
    assert p==p1 & m1==m , " T-Product Can't done for these two tensor"
    AFFT=np.fft.fft(A,axis=2)
    BFFT=np.fft.fft(B,axis=2)
    CFFT=np.zeros((n,n1,p),dtype=complex)
    for i in range(p):
        CFFT[:,:,i]= AFFT[:,:,i] @ BFFT[:,:,i]
    C=np.fft.ifft(CFFT,axis=2)
    return C.real

In [5]:
def FindSymmetric(A):
    n,m,p=A.shape
    assert n==m , "Can't be symmetric"
    AT=np.zeros((m,n,p),dtype=complex)
    AFFT=np.fft.fft(A,axis=2)
    for i in range(p):
        AT[:,:,i]=AFFT[:,:,i].T
    At=np.fft.ifft(AT,axis=2)
    if np.array_equal(A,At):
        return "The tensor is Symmetric"
    else:
        return "The tensor is NOT Symmetric"
    
    

In [6]:
A=np.arange(75).reshape(5,5,3)
FindSymmetric(A)

'The tensor is NOT Symmetric'

In [7]:
A=np.ones(75).reshape(5,5,3)
FindSymmetric(A)

'The tensor is Symmetric'

Let's check whether a given tensor is Diagonal or not?

In [8]:
def FindDiagonal(D):
    n,m,p=I.shape
    A=np.arange(n*m*p).reshape(n,m,p)
    AD=tProduct(A,D)
    DA=tProduct(D,A)
    if np.array_equal(AD,DA):
        return "This is a Diagonal matrix"
    else:
        return "This is NOT a Diagonal matrix"
    

In [54]:
I=np.array([[[1,0,0],[0,0,0],[0,0,0]],[[0,0,0],[3,0,0],[0,0,0]],[[0,0,0],[0,0,0],[4,0,0]]])

In [55]:
I

array([[[1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [3, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [4, 0, 0]]])

In [56]:
FindDiagonal(I)

'This is NOT a Diagonal matrix'

In [47]:
I1=np.array([[[1,0,0],[0,1,0],[0,0,1]],[[1,0,0],[0,1,0],[0,0,1]],[[1,0,0],[0,1,0],[0,0,1]]])

In [48]:
I1

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])

In [49]:
FindDiagonal(I1)

'This is NOT a Diagonal matrix'

Let's check whether a given tensor is Identity or not?

In [15]:
def FindIdentity(I):
    n,m,p=I.shape
    A=np.arange(n*m*p).reshape(n,m,p)
    AI=tProduct(A,I)
    IA=tProduct(I,A)
    if np.array_equal(AI,A):
        return "This is an Identity matrix"
    else:
        return "This is NOT an Identity matrix"
    

In [57]:
I=np.array([[[1,0,0],[0,1,0],[0,0,1]],[[0,0,0],[0,0,0],[0,0,0]],[[0,0,0],[0,0,0],[0,0,0]]])
I

array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [58]:
FindIdentity(I)

'This is NOT an Identity matrix'

In [64]:
I2=np.array([[[1,0,0],[0,0,0],[0,0,0]],[[0,0,0],[1,0,0],[0,0,0]],[[0,0,0],[0,0,0],[1,0,0]]])
I2

array([[[1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [1, 0, 0]]])

In [60]:
FindIdentity(I2)

'This is an Identity matrix'